spring.application.name=Alumnus

# ===== ???? =====
logging.level.root=info
logging.level.com.marler.alumnus=debug
logging.level.org.springframework.web=trace
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ===== ????? =====
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/alumnus_db?useUnicode=true&characterEncoding=utf-8&sslMode=DISABLED&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=21326

# ===== Redis ?? =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0

# ===== ???????????????? =====
spring.web.resources.cache.period=0
spring.web.resources.add-mappings=true

# ===== MyBatis ?? =====
mybatis.mapper-locations=classpath:com/marler/alumnus/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

