spring.application.name=Alumnus

# ===== ????? =====
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/alumnus_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=21326

# ===== MyBatis ?? =====
mybatis.mapper-locations=classpath:com/marler/alumnus/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

